name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "0.15.12"

      - run: npm install spago

      - run: spago build

      - run: spago test